# Config file for cargo deny
# For all options see https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause"
]
private = { ignore = true }
exceptions = [
    { name = "unicode-ident", allow = ["Unicode-3.0"] },
]

[[licenses.clarify]]
crate = "ring"
expression = "MIT AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0x86e2b4b4 }
]

[bans]
multiple-versions = "allow"
